core/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from . import views
from .views import LogoutView

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin/logout/', LogoutView.as_view(), name='admin_logout'),
    path('accounts/', include('django.contrib.auth.urls')),  # Ensure auth URLs are included
    path('tinymce/',include('tinymce.urls')),
    
    path('api/',include('users.urls')),
    path('api/',include('league.urls')),
    path('api/',include('Letter.urls')),
    path('leaguehistory/', include('LeagueHistory.urls')),
    
    path('', views.FixtureList, name='all_match'),
    path('log',views.home,name='log'),
    path('register/',views.regist,name='register'),
    # path('chat/', views.chat_view, name='chat'),
    
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Letter/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from filebrowser.fields import FileBrowseField
from django.conf import settings
# Create your models here.


from django.db import models
from django.conf import settings

class Letter(models.Model):
    title = models.CharField(max_length=250)
    sender = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='sent_letters', on_delete=models.CASCADE)
    receiver = models.ForeignKey(settings.AUTH_USER_MODEL, related_name='received_letters', on_delete=models.CASCADE)
    body = models.TextField()  # a TextField for rich text content
    created = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        # Ensure normal users can only send letters to admins
        if not self.sender.is_staff and not self.receiver.is_staff:
            raise ValueError("Normal users can only send letters to admins.")
        if self.sender.is_staff and self.receiver.is_staff:
            raise ValueError("Admins cannot send letters to other admins.")
        super().save(*args, **kwargs)



# class Media(models.Model):
#     MEDIA_TYPES = (
#         ('image', 'Image'),
#         ('video', 'Video'),
#         ('audio', 'Audio'),
#     )

#     letter = models.ForeignKey(Letter, on_delete=models.CASCADE, related_name='media')
#     media_file = FileBrowseField("File", max_length=200, directory="media/")
#     media_type = models.CharField(max_length=10, choices=MEDIA_TYPES, default='image')

#     def __str__(self):
#         return f"{self.media_type} for post {self.post.title}"

templates/calendar.html
{% load custom_tags %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link href="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css" rel="stylesheet">
    <title>Football Match Calendar</title>
</head>
<body>
    <div class="container mt-5">
        <h1>Football Match Calendar - {{ year }} - {{ month }}</h1>
        <form method="get" class="form-inline mb-3">
            <div class="form-group">
                <label for="month" class="mr-2">Select Month:</label>
                <select id="month" name="month" class="form-control mr-2">
                    {% for num, name in months %}
                        <option value="{{ num }}" {% if num == month %}selected{% endif %}>{{ name }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="form-group">
                <label for="year" class="mr-2">Select Year:</label>
                <input type="number" id="year" name="year" value="{{ year }}" class="form-control mr-2" min="1900" max="2100">
            </div>
            <button type="submit" class="btn btn-primary">Go</button>
        </form>
        <table class="table table-bordered">
            <thead class="thead-light">
                <tr>
                    <th>Sun</th>
                    <th>Mon</th>
                    <th>Tue</th>
                    <th>Wed</th>
                    <th>Thu</th>
                    <th>Fri</th>
                    <th>Sat</th>
                </tr>
            </thead>
            <tbody>
                {% for week in month_calendar %}
                <tr>
                    {% for day in week %}
                    {% if day %}
                    {% with day_match=match_days|get_item:day %}
                    <td{% if day_match %} style="background-color: lightblue;"{% endif %}>
                        <div>{{ day }}</div>
                        {% if day_match %}
                            {% for match in day_match %}
                                <div class="d-flex align-items-center">
                                    <img src="{{ match.home_logo.url }}" alt="{{ match.home_team }} logo" class="mr-2" style="width: 20px; height: 20px;">
                                    vs
                                    <img src="{{ match.away_logo.url }}" alt="{{ match.away_team }} logo" class="ml-2" style="width: 20px; height: 20px;">
                                </div>
                            {% endfor %}
                        {% endif %}
                    </td>
                    {% endwith %}
                    {% else %}
                    <td></td>
                    {% endif %}
                    {% endfor %}
                </tr>
                {% endfor %}
            </tbody>
        </table>
    </div>

    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

templates/chat.html
<div id="letter" class="container mt-5 content" style="display:none;">
    <div class="row">
        <div class="col-lg-8 offset-lg-2">
            <div class="card">
                <div class="card-body">
                    {{ form.media }}
                    <h3 class="card-title text-center mb-4">Create Letter</h3>
                    <form method="post">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="id_title">Title:</label>
                            {{ form.title }}
                        </div>
                        <div class="mb-3">
                            <label for="id_title">Receiver:</label>
                            {{ form.receiver }}
                        </div>
            
                        <div class="textarea-container">
                            <label for="id_body">Letter:</label>
                            {{ form.body }}
                        </div>
                        <button type="submit" class="btn btn-primary w-100">Send</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    
    <div class="row mt-5">
        <div class="col-md-12 mb-4">
            <h3 class="mb-3">Received Letters</h3>
            {% if received_letters %}
                <ul class="list-group">
                    {% for receiver in received_letters %}
                        <li class="list-group-item">
                            <a href="{% url 'letter_detail' receiver.id %}" class="btn btn-link">{{ receiver.title }}</a>
                        </li>
                    {% endfor %}
                </ul>
            {% else %}
                <p class="alert alert-info">No Received Letters at the moment.</p>
            {% endif %}
        </div>
        
        <div class="col-md-12 mb-4">
            <h3 class="mb-3">Sent Letters</h3>
            {% if sent_letters %}
                <ul class="list-group">
                    {% for sender in sent_letters %}
                        <li class="list-group-item">
                            <a href="{% url 'letter_detail' sender.id %}" class="btn btn-link">{{ sender.title }}</a>
                        </li>
                    {% endfor %}
                </ul>
            {% else %}
                <p class="alert alert-info">No Sent Letters at the moment.</p>
            {% endif %}
        </div>
    </div>
</div>


<div id="letter" class="container mt-5 content" style="display:none;">
    <div class="row">
        <div class="container">
            {{ form.media }}
            <h1>Create Letter</h1>
            <form method="post">
                {% csrf_token %}
                <div>
                    <label for="id_title">Title:</label>
                    {{ form.title }}
                </div>
                <div>
                    <label for="id_title">Receiver:</label>
                    {{ form.receiver }}
                </div>
    
                <div class="textarea-container">
                    <label for="id_body">Letter:</label>
                    {{ form.body }}
                </div>
                <button type="submit">Send</button>
            </form>
        </div>
    </div>
    <div class="col-md-12 mb-4">
        <h1 class="mb-3">Received Letters</h1>
        {% if received_letters %}
            <ul class="list-group">
                {% for receiver in received_letters %}
                    <li class="list-group-item">
                        <a href="{% url 'letter_detail' receiver.id %}" class="btn btn-link">{{ receiver.title }}</a>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p class="alert alert-warning">No Received Letters at the moment.</p>
        {% endif %}
    </div>
    
    <div class="col-md-12 mb-4">
        <h1 class="mb3">Sent Letters</h1>
        {% if sent_letters %}
            <ul class="list-group">
                {% for sender in sent_letters %}
                    <li class="list-group-item">
                        <a href="{% url 'letter_detail' sender.id %}" class="btn btn-link">{{ sender.title }}</a>
                    </li>
                {% endfor %}
            </ul>
        {% else %}
            <p class="alert alert-warning">No Sent Letters at the moment.</p>
        {% endif %}
    </div>
</div>

templates/index.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
  <title>[NBC Premier League] - Welcome</title>
 
  <link rel="stylesheet" href="{% static 'css/login1.css' %}">
  <link href="https://unpkg.com/boxicons@2.0.7/css/boxicons.min.css" rel="stylesheet" />
  
</head>
<body>
  {% if error_message %}
    <div class="alert alert-danger">
        {{ error_message }}
    </div>
  {% endif %}
  <header>
    <h1>Welcome to NBC Premier League</h1>
  </header>

  {% comment %} login info {% endcomment %}
  <div id="logindetails" >
    <div class="login_box">
      <form id="login-form" method="POST">
        {% csrf_token %}
        <h1>Login</h1>
        <div class="input_box">
          <input type="email" name="email" placeholder="Email" required>
        </div>

        <div class="input_box">
          <!-- Password input field -->
          <input type="password" id="password-input" name="password" placeholder="Password" required>
          <!-- Eye icon for toggling password visibility -->
          <i id="toggle-password" class="bx bx-show"></i>
        </div>
      

        <div class="remember">
            <input type="checkbox">
            <label for="">remember me</label>
        </div>

        <div class="forget"><a href="#">forget password ?</a></div>

        <div class="log">
          <button type="submit">Login</button>
        </div>

        <div class="reg">
            <p>don't have an account <a href="{% url 'register' %}">Register</a></p>
        </div>
      </form>

    </div>
    
  </div>

  <footer>
    <p>&copy; 2023 Mango Ltd. All rights reserved.</p>
  </footer>
</body>


<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>


<script>
  $(document).ready(function() {
    $('#login-form').submit(function(e) {
        e.preventDefault(); // Prevent form submission

        // Serialize the form data
        var formData = $(this).serialize();

        // Make the AJAX request to the API endpoint
        $.ajax({
            url: '/api/login/', // Replace with your actual API endpoint URL
            type: 'POST',
            data: formData,
            success: function(response) {
                // Handle the successful login
                console.log(response);
                alert('Login successful');
                // Redirect to the appropriate URL
                window.location.href = '/api/TeamManager'; // Replace with the appropriate URL for the dashboard page
            },
            error: function(xhr, textStatus, errorThrown) {
                // Handle the login error
                console.log(xhr.responseJSON);
                var errorData = xhr.responseJSON;
                var errorMessage = 'Login failed. Please check your credentials.';
                if (errorData.detail === 'user not found') {
                    errorMessage = 'User does not exist.';
                }
                alert(errorMessage);
            }
        });
    });

    // Get references to the password input field and the eye icon
    const passwordInput = document.getElementById('password-input');
    const togglePassword = document.getElementById('toggle-password');

    // Add click event listener to the eye icon
    togglePassword.addEventListener('click', function() {
        // Toggle the type attribute of the password input field between 'password' and 'text'
        const type = passwordInput.getAttribute('type') === 'password' ? 'text' : 'password';
        passwordInput.setAttribute('type', type);

        // Toggle the eye icon's class between 'bx-show' and 'bx-hide' to change the icon
        togglePassword.classList.toggle('bx-show');
        togglePassword.classList.toggle('bx-hide');
    });

  });
  
</script>

</html>

templates/letter_detail.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
    <style>
        .container {
            max-width: 900px;
            margin: 20px auto;
            background-color: #fff;
            padding: 20px;
            border-radius: 8px;
            box-shadow: 0 2px 5px rgba(0, 0, 0, 0.1);
        }
        .back-arrow {
            display: flex;
            align-items: center;
            margin-bottom: 20px;
        }
        .back-arrow a {
            text-decoration: none;
            color: #007bff;
            font-size: 20px;
        }
        .back-arrow a:hover {
            text-decoration: underline;
        }
        h1 {
            color: #007bff;
            margin-top: 0;
        }
        p {
            margin-top: 5px;
            margin-bottom: 10px;
        }
        strong {
            font-weight: bold;
        }
        .description {
            margin-top: 15px;
        }
    </style>
</head>
<body>
    <div class="container">
        <div class="back-arrow">
            <a href="{% url 'team_manager_dashboard' %}">&larr; Back to Dashboard</a>
        </div>
        <h1>{{ details.title }}</h1>
        <p><strong>From:</strong> {{ details.sender }} <strong>To:</strong> {{ details.receiver }}</p>
        <p><strong>Date:</strong> {{ details.created }}</p>
        <div class="description">
            <strong>LETTER:</strong>
            <p>{{ details.body|safe }}</p>
        </div>
    </div>
</body>
</html>